apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "clear-log-activity"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
    - index: 0
      type: int
    - index: 1
      type: "string"
    - index: 2
      type: int
    selectors:
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
        - "/var/log/"
      matchActions:
      - action: Post